"""group event capacity and blocks_host

Revision ID: 224680d3d200
Revises: 951eebb7ce67
Create Date: 2026-06-28 00:11:56.358353

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "224680d3d200"
down_revision: str | Sequence[str] | None = "951eebb7ce67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("blocks_host", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "event_types", sa.Column("capacity", sa.SmallInteger(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###

    # Recreate the no-overlap guarantee so it ignores non-blocking (group) bookings.
    op.execute("ALTER TABLE bookings DROP CONSTRAINT no_overlap_per_host")
    op.execute(
        "ALTER TABLE bookings ADD CONSTRAINT no_overlap_per_host "
        "EXCLUDE USING gist (host_id WITH =, period WITH &&) "
        "WHERE (status = 'confirmed' AND blocks_host)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE bookings DROP CONSTRAINT no_overlap_per_host")
    op.execute(
        "ALTER TABLE bookings ADD CONSTRAINT no_overlap_per_host "
        "EXCLUDE USING gist (host_id WITH =, period WITH &&) WHERE (status = 'confirmed')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_types", "capacity")
    op.drop_column("bookings", "blocks_host")
    # ### end Alembic commands ###
