"""caldav connections and external busy

Revision ID: 2f53e39f1743
Revises: 392bd3452e18
Create Date: 2026-06-27 21:48:17.883827

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f53e39f1743"
down_revision: str | Sequence[str] | None = "392bd3452e18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caldav_connections",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("server_url", sa.String(length=2048), nullable=False),
        sa.Column("username", sa.String(length=320), nullable=False),
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column("calendar_url", sa.String(length=2048), nullable=False),
        sa.Column("calendar_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'needs_reauth')",
            name=op.f("ck_caldav_connections_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_caldav_connections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_caldav_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_caldav_connections")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_caldav_connections_organization_id")
        ),
    )
    op.create_table(
        "external_busy",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "period",
            postgresql.TSTZRANGE(),
            sa.Computed("tstzrange(start_at, end_at, '[)')", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["caldav_connections.id"],
            name=op.f("fk_external_busy_connection_id_caldav_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
            name=op.f("fk_external_busy_host_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_external_busy_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_busy")),
    )
    op.create_index(
        "ix_external_busy_org_period",
        "external_busy",
        ["organization_id", "period"],
        unique=False,
        postgresql_using="gist",
    )
    op.add_column("bookings", sa.Column("external_event_uid", sa.String(length=512), nullable=True))
    op.add_column(
        "bookings", sa.Column("external_event_url", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###

    # Row-Level Security on the new tenant-scoped tables (same default-deny policy as the rest).
    for table in ("caldav_connections", "external_busy"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} USING "
            f"(organization_id = current_setting('app.current_org_id', true)::uuid) "
            f"WITH CHECK (organization_id = current_setting('app.current_org_id', true)::uuid)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "external_event_url")
    op.drop_column("bookings", "external_event_uid")
    op.drop_index(
        "ix_external_busy_org_period", table_name="external_busy", postgresql_using="gist"
    )
    op.drop_table("external_busy")
    op.drop_table("caldav_connections")
    # ### end Alembic commands ###
