"""auth tokens

Revision ID: 589e7e29eddb
Revises: 5e6aae2d7606
Create Date: 2026-06-26 23:30:50.933550

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "589e7e29eddb"
down_revision: str | Sequence[str] | None = "5e6aae2d7606"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_verification_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verification_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_email_verification_tokens_token_hash")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    # ### end Alembic commands ###

    # Sign-up provisioning. Creating an organization requires bypassing the RLS WITH CHECK
    # (the creator is not yet a member), so this runs SECURITY DEFINER (as the function owner,
    # which is the privileged migration role). It atomically creates the user, credentials,
    # organization and the owner membership. The app role only gets EXECUTE on it.
    op.execute(
        """
        CREATE FUNCTION provision_account(
            p_email text, p_name text, p_password_hash text, p_org_name text, p_org_slug text
        ) RETURNS TABLE(user_id uuid, organization_id uuid)
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            v_user_id uuid;
            v_org_id uuid;
        BEGIN
            INSERT INTO users (email, name, timezone)
                VALUES (p_email, p_name, 'UTC')
                RETURNING id INTO v_user_id;
            INSERT INTO user_credentials (user_id, password_hash)
                VALUES (v_user_id, p_password_hash);
            INSERT INTO organizations (name, slug)
                VALUES (p_org_name, p_org_slug)
                RETURNING id INTO v_org_id;
            INSERT INTO memberships (organization_id, user_id, role)
                VALUES (v_org_id, v_user_id, 'owner');
            RETURN QUERY SELECT v_user_id, v_org_id;
        END;
        $$;
        """
    )
    op.execute("REVOKE ALL ON FUNCTION provision_account(text, text, text, text, text) FROM PUBLIC")
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ghostcal_app') THEN
                GRANT EXECUTE ON FUNCTION
                    provision_account(text, text, text, text, text) TO ghostcal_app;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS provision_account(text, text, text, text, text)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_tokens")
    op.drop_table("email_verification_tokens")
    # ### end Alembic commands ###
