"""event type kind and host pool

Revision ID: 5b4f57c2f794
Revises: 9f70c2331127
Create Date: 2026-06-27 23:28:39.765459

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b4f57c2f794"
down_revision: str | Sequence[str] | None = "9f70c2331127"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_type_hosts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("event_type_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["event_types.id"],
            name=op.f("fk_event_type_hosts_event_type_id_event_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_event_type_hosts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_event_type_hosts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_type_hosts")),
        sa.UniqueConstraint(
            "event_type_id", "user_id", name=op.f("uq_event_type_hosts_event_type_id")
        ),
    )
    op.add_column(
        "event_types",
        sa.Column("kind", sa.String(length=20), server_default="solo", nullable=False),
    )
    # ### end Alembic commands ###

    # RLS: same default-deny tenant isolation as the other tenant tables.
    op.execute("ALTER TABLE event_type_hosts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE event_type_hosts FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON event_type_hosts USING "
        "(organization_id = current_setting('app.current_org_id', true)::uuid) "
        "WITH CHECK (organization_id = current_setting('app.current_org_id', true)::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_types", "kind")
    op.drop_table("event_type_hosts")
    # ### end Alembic commands ###
