"""event type schedule fk

Revision ID: 5f1ac9e25fd7
Revises: 589e7e29eddb
Create Date: 2026-06-26 23:48:34.368935

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f1ac9e25fd7"
down_revision: str | Sequence[str] | None = "589e7e29eddb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event_types", sa.Column("schedule_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_event_types_schedule_id_availability_schedules"),
        "event_types",
        "availability_schedules",
        ["schedule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_event_types_schedule_id_availability_schedules"), "event_types", type_="foreignkey"
    )
    op.drop_column("event_types", "schedule_id")
    # ### end Alembic commands ###
