"""event type redirect url

Revision ID: 84db310aacb3
Revises: d97d181b54e5
Create Date: 2026-06-28 01:44:03.081479

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84db310aacb3"
down_revision: str | Sequence[str] | None = "d97d181b54e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event_types", sa.Column("redirect_url", sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_types", "redirect_url")
    # ### end Alembic commands ###
