"""organization invitations

Revision ID: 86b213c4e79a
Revises: 15a58d63eba0
Create Date: 2026-06-27 22:58:48.762720

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86b213c4e79a"
down_revision: str | Sequence[str] | None = "15a58d63eba0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_invitations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member')",
            name=op.f("ck_organization_invitations_invitation_role_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["users.id"],
            name=op.f("fk_organization_invitations_accepted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_organization_invitations_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_organization_invitations_token_hash")),
    )
    op.create_index(
        "uq_pending_invitation_per_email",
        "organization_invitations",
        ["organization_id", "email"],
        unique=True,
        postgresql_where=sa.text("accepted_at IS NULL"),
    )
    # ### end Alembic commands ###

    # Row-Level Security: same default-deny tenant isolation as the other tenant tables.
    op.execute("ALTER TABLE organization_invitations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organization_invitations FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON organization_invitations USING "
        "(organization_id = current_setting('app.current_org_id', true)::uuid) "
        "WITH CHECK (organization_id = current_setting('app.current_org_id', true)::uuid)"
    )

    # (organization_id, role) of a user's primary membership — lets us resolve the acting user's
    # role without an org context (memberships is RLS-protected). Same ordering as
    # user_primary_organization so the org matches.
    op.execute(
        """
        CREATE FUNCTION user_primary_membership(p_user_id uuid)
        RETURNS TABLE(organization_id uuid, role text)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public
        AS $$
            SELECT organization_id, role
            FROM memberships
            WHERE user_id = p_user_id
            ORDER BY created_at
            LIMIT 1
        $$;
        """
    )

    # Preview an invitation by token hash for the accept page, before the invitee is a member
    # (RLS would otherwise hide it). Returns nothing if invalid / expired / already used.
    op.execute(
        """
        CREATE FUNCTION organization_invitation_preview(p_token_hash text)
        RETURNS TABLE(organization_id uuid, organization_name text, email text, role text)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public
        AS $$
            SELECT i.organization_id, o.name, i.email, i.role
            FROM organization_invitations i
            JOIN organizations o ON o.id = i.organization_id
            WHERE i.token_hash = p_token_hash
              AND i.accepted_at IS NULL
              AND i.expires_at > now()
        $$;
        """
    )

    # Accept an invitation: add the membership (idempotent) and mark it accepted. Returns the
    # organization_id, or NULL if the token is invalid / expired / already used.
    op.execute(
        """
        CREATE FUNCTION accept_organization_invitation(p_token_hash text, p_user_id uuid)
        RETURNS uuid
        LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public
        AS $$
        DECLARE
            v_org uuid;
            v_role text;
        BEGIN
            SELECT organization_id, role INTO v_org, v_role
            FROM organization_invitations
            WHERE token_hash = p_token_hash
              AND accepted_at IS NULL
              AND expires_at > now()
            FOR UPDATE;

            IF v_org IS NULL THEN
                RETURN NULL;
            END IF;

            INSERT INTO memberships (organization_id, user_id, role)
            VALUES (v_org, p_user_id, v_role)
            ON CONFLICT (organization_id, user_id) DO NOTHING;

            UPDATE organization_invitations
            SET accepted_at = now(), accepted_by_user_id = p_user_id
            WHERE token_hash = p_token_hash;

            RETURN v_org;
        END
        $$;
        """
    )

    for fn in (
        "user_primary_membership(uuid)",
        "organization_invitation_preview(text)",
        "accept_organization_invitation(text, uuid)",
    ):
        op.execute(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC")
        op.execute(
            "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ghostcal_app') "
            f"THEN GRANT EXECUTE ON FUNCTION {fn} TO ghostcal_app; END IF; END $$;"
        )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS accept_organization_invitation(text, uuid)")
    op.execute("DROP FUNCTION IF EXISTS organization_invitation_preview(text)")
    op.execute("DROP FUNCTION IF EXISTS user_primary_membership(uuid)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pending_invitation_per_email",
        table_name="organization_invitations",
        postgresql_where=sa.text("accepted_at IS NULL"),
    )
    op.drop_table("organization_invitations")
    # ### end Alembic commands ###
