"""collective booking group id

Revision ID: 951eebb7ce67
Revises: 5b4f57c2f794
Create Date: 2026-06-28 00:03:59.822241

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "951eebb7ce67"
down_revision: str | Sequence[str] | None = "5b4f57c2f794"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("collective_group_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_bookings_collective_group_id"), "bookings", ["collective_group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_collective_group_id"), table_name="bookings")
    op.drop_column("bookings", "collective_group_id")
    # ### end Alembic commands ###
