"""booking reminders

Revision ID: 9f70c2331127
Revises: ad45130d7708
Create Date: 2026-06-27 23:20:41.858190

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f70c2331127"
down_revision: str | Sequence[str] | None = "ad45130d7708"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_reminders",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("minutes_before", sa.Integer(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_reminders_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_booking_reminders_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_reminders")),
        sa.UniqueConstraint(
            "booking_id", "minutes_before", name=op.f("uq_booking_reminders_booking_id")
        ),
    )
    # ### end Alembic commands ###

    # RLS: same default-deny tenant isolation as the other tenant tables.
    op.execute("ALTER TABLE booking_reminders ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE booking_reminders FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON booking_reminders USING "
        "(organization_id = current_setting('app.current_org_id', true)::uuid) "
        "WITH CHECK (organization_id = current_setting('app.current_org_id', true)::uuid)"
    )

    # Reminders due now for the given offsets (minutes before start), not yet sent. Cross-tenant
    # (the reminder worker has no org context), so SECURITY DEFINER. Returns the email fields too.
    op.execute(
        """
        CREATE FUNCTION due_booking_reminders(p_offsets int[])
        RETURNS TABLE(
            booking_id uuid, organization_id uuid, minutes_before int,
            invitee_name text, invitee_email text, invitee_timezone text,
            event_title text, host_name text, host_email text, host_timezone text,
            location_type text, start_at timestamptz, end_at timestamptz
        )
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public
        AS $$
            SELECT b.id, b.organization_id, ofs.minutes_before,
                   b.invitee_name, b.invitee_email, b.invitee_timezone,
                   et.title, u.name, u.email, u.timezone,
                   et.location_type, b.start_at, b.end_at
            FROM bookings b
            JOIN event_types et ON et.id = b.event_type_id
            JOIN users u ON u.id = b.host_id
            CROSS JOIN unnest(p_offsets) AS ofs(minutes_before)
            WHERE b.status = 'confirmed'
              AND b.start_at > now()
              AND b.start_at - make_interval(mins => ofs.minutes_before) <= now()
              -- Skip offsets whose moment already passed when the booking was made (e.g. a 24h
              -- reminder for a meeting booked 30 min in advance).
              AND b.start_at - make_interval(mins => ofs.minutes_before) >= b.created_at
              AND NOT EXISTS (
                  SELECT 1 FROM booking_reminders r
                  WHERE r.booking_id = b.id AND r.minutes_before = ofs.minutes_before
              )
        $$;
        """
    )

    # Atomically claim a (booking, offset) reminder. Returns true if this call inserted it (so the
    # caller should send), false if it was already claimed — at-most-once even with concurrent runs.
    op.execute(
        """
        CREATE FUNCTION claim_booking_reminder(
            p_booking_id uuid, p_organization_id uuid, p_minutes_before int
        )
        RETURNS boolean
        LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public
        AS $$
        DECLARE
            v_count int;
        BEGIN
            INSERT INTO booking_reminders (organization_id, booking_id, minutes_before)
            VALUES (p_organization_id, p_booking_id, p_minutes_before)
            ON CONFLICT (booking_id, minutes_before) DO NOTHING;
            GET DIAGNOSTICS v_count = ROW_COUNT;
            RETURN v_count > 0;
        END
        $$;
        """
    )

    for fn in ("due_booking_reminders(int[])", "claim_booking_reminder(uuid, uuid, int)"):
        op.execute(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC")
        op.execute(
            "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ghostcal_app') "
            f"THEN GRANT EXECUTE ON FUNCTION {fn} TO ghostcal_app; END IF; END $$;"
        )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS claim_booking_reminder(uuid, uuid, int)")
    op.execute("DROP FUNCTION IF EXISTS due_booking_reminders(int[])")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booking_reminders")
    # ### end Alembic commands ###
