"""audit log

An append-only record of security-relevant actions: who did what, to whom, when.

Hand-written, not autogenerated — the RLS policy, the append-only grants and the SECURITY DEFINER
writer below are all raw SQL that ``--autogenerate`` would not produce and would later propose
dropping (see ``migrations/env.py``).

Two properties this table is built around:

1. **Append-only in the database, not by convention.** The application role gets INSERT and SELECT
   and is denied UPDATE and DELETE. An attacker who reaches the app connection can add noise to the
   log but cannot quietly remove the entry recording what they did — which is the whole point of
   keeping one.

2. **It records that something happened, never the content it happened to.** ``details`` holds
   identifiers, role names and counts. Event titles, invitee answers and task content are sealed
   to keys the server does not hold, and an audit log is exactly the wrong place to start
   accumulating the plaintext this product exists to avoid holding.

Rows outlive their organization deliberately: ``organization_id`` is nullable with ON DELETE SET
NULL, so deleting an org does not erase the record that it was deleted.

Revision ID: a1c7d4e90b23
Revises: d3b8f1a04e77
Create Date: 2026-07-20 14:05:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a1c7d4e90b23"
down_revision: str | Sequence[str] | None = "d3b8f1a04e77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        # Nullable: account-level actions (login, account deletion) belong to no organization, and
        # an org's rows must survive the org being deleted.
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        # Nullable: a failed login has no authenticated actor, and a deleted user leaves records.
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("target", sa.String(255), nullable=True),
        sa.Column(
            "details", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    # The query this table exists to answer: "what happened in this org, most recent first".
    op.create_index(
        "ix_audit_events_org_time",
        "audit_events",
        ["organization_id", sa.text("created_at DESC")],
    )

    op.execute("ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_events FORCE ROW LEVEL SECURITY")
    # Org-scoped reads, as everywhere else. Account-level rows (organization_id IS NULL) are
    # visible to nobody through the app connection — they are for the operator, via the admin role.
    # NULLIF is not decoration — see migration b2d8f30c17ae, which swept every existing policy for
    # exactly this. `set_config(..., is_local => true)` reverts the GUC to the empty string at
    # commit, not to unset, so on a recycled connection `''::uuid` *raises* instead of matching
    # nothing: an unbound read becomes a 500 rather than an empty result. That sweep ran nine
    # revisions ago and will not run again, so a new policy has to get this right on its own.
    op.execute(
        "CREATE POLICY tenant_isolation ON audit_events USING "
        "(organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) "
        "WITH CHECK (organization_id IS NULL OR "
        "organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)"
    )

    # Append-only, enforced by grants rather than hoped for. The app role never revises history.
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ghostcal_app') THEN
            REVOKE UPDATE, DELETE ON audit_events FROM ghostcal_app;
            GRANT INSERT, SELECT ON audit_events TO ghostcal_app;
          END IF;
        END
        $$;
        """
    )

    # Account-level events have no org context, and the tenant policy would reject them on a
    # plain session. SECURITY DEFINER so the app can record a login or an account deletion
    # without being handed a way to write arbitrary org-scoped rows.
    #
    # `p_actor` is written as given: there is no session GUC carrying the authenticated user, so
    # the function cannot verify it and the caller must pass a server-derived id, never one from
    # a request body. Callers today satisfy that; it is stated because the next one has to too.
    op.execute(
        """
        CREATE FUNCTION record_account_audit_event(
            p_actor uuid, p_action text, p_target text, p_details jsonb
        ) RETURNS void
        LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
            INSERT INTO audit_events (organization_id, actor_user_id, action, target, details)
            VALUES (NULL, p_actor, p_action, p_target, COALESCE(p_details, '{}'::jsonb));
        $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ghostcal_app') THEN
            GRANT EXECUTE ON FUNCTION
              record_account_audit_event(uuid, text, text, jsonb) TO ghostcal_app;
          END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS record_account_audit_event(uuid, text, text, jsonb)")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON audit_events")
    op.drop_index("ix_audit_events_org_time", table_name="audit_events")
    op.drop_table("audit_events")
