// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`

/// Dérive la clé de coffre depuis une phrase et un sel.
///
/// Le vecteur qui l'éprouve vient de `hash-wasm`, la bibliothèque Argon2 du navigateur —
/// pas du cœur. C'est ce qui rend le test utile : il vérifie que Dart obtient ce que le
/// web obtient, et non que le cœur est cohérent avec lui-même.
Future<Uint8List> deriverCle({
  required String phrase,
  required List<int> sel,
}) => RustLib.instance.api.crateApiCoeurDeriverCle(phrase: phrase, sel: sel);

/// Scelle un contenu vers une clé publique, dans un domaine donné.
Future<String> scellerVers({
  required String publique,
  required List<int> clair,
  required String domaine,
}) => RustLib.instance.api.crateApiCoeurScellerVers(
  publique: publique,
  clair: clair,
  domaine: domaine,
);

/// Ouvre un contenu scellé. Échoue si le domaine ne correspond pas — c'est cette
/// séparation qui empêche ghostcal et ghostmail de lire les données l'un de l'autre.
Future<Uint8List> ouvrirSceau({
  required String privee,
  required String blob,
  required String domaine,
}) => RustLib.instance.api.crateApiCoeurOuvrirSceau(
  privee: privee,
  blob: blob,
  domaine: domaine,
);

/// Déballe un contenu chiffré symétriquement — l'enveloppe d'une clé privée
/// d'organisation, scellée sous la clé dérivée de la phrase.
Future<Uint8List> dechiffrerSymetrique({
  required List<int> cle,
  required String blob,
}) => RustLib.instance.api.crateApiCoeurDechiffrerSymetrique(
  cle: cle,
  blob: blob,
);

/// L'opération inverse, pour réenvelopper une clé lors d'un changement de phrase.
Future<String> chiffrerSymetrique({
  required List<int> cle,
  required List<int> clair,
}) => RustLib.instance.api.crateApiCoeurChiffrerSymetrique(
  cle: cle,
  clair: clair,
);

Future<PaireDeCles> genererPaire() =>
    RustLib.instance.api.crateApiCoeurGenererPaire();

/// L'erreur telle que Dart la verra.
///
/// Le type d'erreur du cœur ne traverse pas : il porte des variantes qui n'ont de sens
/// qu'en Rust. On rend un message, comme le fait déjà le binding UniFFI — ce qui compte,
/// c'est que l'échec soit un échec, pas qu'il soit typé de l'autre côté.
class ErreurDuCoeur implements FrbException {
  final String message;

  const ErreurDuCoeur({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ErreurDuCoeur &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// Une paire de clés X25519, en base64.
class PaireDeCles {
  final String publique;
  final String privee;

  const PaireDeCles({required this.publique, required this.privee});

  @override
  int get hashCode => publique.hashCode ^ privee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaireDeCles &&
          runtimeType == other.runtimeType &&
          publique == other.publique &&
          privee == other.privee;
}
